In [82]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer, label_binarize
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression




### Ejercicio 1:

In [75]:
data=pd.read_csv("dataset_36_segment.csv")
data


region-centroid-col  region-centroid-row  region-pixel-count  \
0                     218                  178                   9   
1                     113                  130                   9   
2                     202                   41                   9   
3                      32                  173                   9   
4                      61                  197                   9   
...                   ...                  ...                 ...   
2305                   30                  102                   9   
2306                  143                   24                   9   
2307                   80                   72                   9   
2308                   98                  133                   9   
2309                   19                  147                   9   

      short-line-density-5  short-line-density-2  vedge-mean  vegde-sd  \
0                 0.111111                   0.0    0.833333  0.547722   
1                 0.000000                   0.0    0.277778  0.250924   
2                 0.000000                   0.0    0.944448  0.772202   
3                 0.000000                   0.0    1.722220  1.781590   
4                 0.000000                   0.0    1.444440  1.515350   
...                    ...                   ...         ...       ...   
2305              0.000000                   0.0    1.222220  0.118518   
2306              0.000000                   0.0    1.277780  0.907406   
2307              0.000000                   0.0    1.222220  1.003700   
2308              0.000000                   0.0    0.555555  0.172133   
2309              0.000000                   0.0    0.222222  0.074074   

      hedge-mean  hedge-sd  intensity-mean  rawred-mean  rawblue-mean  \
0       1.111110  0.544331       59.629600     52.44440      75.22220   
1       0.333333  0.365148        0.888889      0.00000       2.55556   
2       1.111110  1.025600      123.037000    111.88900     139.77800   
3       9.000000  6.749490       43.592600     39.55560      52.88890   
4       2.611110  1.925460       49.592600     44.22220      61.55560   
...          ...       ...             ...          ...           ...   
2305    1.333330  0.800000       20.259300     20.33330      25.00000   
2306    0.888888  1.140750      127.630000    117.66700     141.66700   
2307    1.444440  1.167460       59.000000     51.33330      74.44440   
2308    0.388889  0.327731        0.962963      0.00000       2.77778   
2309    0.500000  0.077778        4.148150      3.88889       6.66667   

      rawgreen-mean  exred-mean  exblue-mean  exgreen-mean  value-mean  \
0         51.222200  -21.555600     46.77780     -25.22220    75.22220   
1          0.111111   -2.666670      5.00000      -2.33333     2.55556   
2        117.444000  -33.444400     50.22220     -16.77780   139.77800   
3         38.333300  -12.111100     27.88890     -15.77780    52.88890   
4         43.000000  -16.111100     35.88890     -19.77780    61.55560   
...             ...         ...          ...           ...         ...   
2305      15.444400    0.222222     14.22220     -14.44440    25.00000   
2306     123.556000  -29.888900     42.11110     -12.22220   141.66700   
2307      51.222200  -23.000000     46.33330     -23.33330    74.44440   
2308       0.111111   -2.888890      5.44444      -2.55556     2.77778   
2309       1.888890   -0.777778      7.55556      -6.77778     7.00000   

      saturation-mean  hue-mean      class  
0            0.318996  -2.04055       path  
1            1.000000  -2.12325    foliage  
2            0.199347  -2.29992        sky  
3            0.266914  -1.99886       path  
4            0.302925  -2.02227       path  
...               ...       ...        ...  
2305         0.381059  -1.55510  brickface  
2306         0.169397  -2.34925        sky  
2307         0.314606  -2.09022     cement  
2308         1.000000  -2.12325    foliage  
2309         0.

### Ejercicio 2:

In [76]:
# regresion lineal hold out 2/3, 1/3

In [77]:
# Y es el objetivo, la clase

y = data["class"]
y

0            path
1         foliage
2             sky
3            path
4            path
          ...    
2305    brickface
2306          sky
2307       cement
2308      foliage
2309    brickface
Name: class, Length: 2310, dtype: object

In [78]:
escala = MinMaxScaler()  # transformamos a intervalo (0,1)
X = data.drop(columns=["class"])
X = escala.fit_transform(X)
clase = data.drop(columns=["class"])
clase.shape, X.shape, np.min(X,axis=0), np.max(X,axis=0) #combprobación de escalado.

((2310, 19),
 (2310, 19),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]),
 array([1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]))

In [79]:
y_binario = LabelBinarizer().fit_transform(y)
y_binario.astype(float)

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X, y_binario, test_size=1/3, stratify=y_binario, random_state=0)


In [81]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape


((1540, 19), (770, 19), (1540, 7), (770, 7))

In [84]:

y_predict = np.zeros(y_test.shape)
#con esto voy poniendo a 1 la columna que corresponde al valor asociado a la clase anteriormente mediante labelBinarizer.
for i in range (y_train.shape[1]):
    model = LinearRegression()
    model.fit(X_train, y_train[:,i])
    y_predict[:,i] = model.predict(X_test)
y_test.shape[0]

770

In [85]:
y_predict

array([[ 0.10558569,  0.21820016, -0.06236197, ...,  0.24741115,
         0.69440921, -0.12032336],
       [ 0.02989432,  0.16954174,  0.0799653 , ...,  0.40564948,
         0.13505761,  0.1749463 ],
       [ 0.29976794,  0.18358958,  0.09322737, ...,  0.14863849,
        -0.0102247 ,  0.19818212],
       ...,
       [-0.08011771,  0.18327264, -0.1458935 , ...,  0.25335999,
         0.86601057, -0.0634468 ],
       [ 0.28045593,  0.18639295,  0.18050684, ...,  0.03837892,
         0.09195144,  0.2114863 ],
       [ 0.2501261 ,  0.15608622,  0.04831618, ...,  0.03726147,
        -0.10536121,  0.30380139]])

In [86]:
print("Tasa de aciertos =",np.sum(np.argmax(y_predict, axis=1) == np.argmax(y_test, axis=1))/y_test.shape[0])


Tasa de aciertos = 0.7363636363636363


In [66]:
print("\nMatriz de Confusión:\n", confusion_matrix(np.argmax(y_test, axis=1), np.argmax(y_predict, axis=1)))



Matriz de Confusión:
 [[108   0   2   0   0   0   0]
 [ 24  36   3   0  26   0  21]
 [  1   3  95   0   0   0  11]
 [  0   0   0 110   0   0   0]
 [  0   0   0   0 110   0   0]
 [  0   0   0   0   0 110   0]
 [  1   4  31   0   0   0  74]]


### Ejercicio 3:

In [13]:
# En este caso me pide lo mismo pero con estratificación, entonces usaré la función StratifiedKFold() de sklearn

In [89]:
precision = 0
cv = StratifiedKFold(n_splits=10)
print("La tasa de error de cada uno de los 10 pliegues es: \n")
for train_index, test_index in cv.split(X,y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y_binario[train_index], y_binario[test_index]
    y_predict = np.zeros(y_test.shape)
    for i in range(y_train.shape[1]):
        lr = SGDRegressor()
        lr.fit(X_train, y_train[:,i])
        y_predict[:,i] = lr.predict(X_test)
    print(np.sum(np.argmax(y_predict, axis=1) == np.argmax(y_test, axis=1))/y_test.shape[0])
    precision += np.sum(np.argmax(y_predict, axis=1) == np.argmax(y_test, axis=1))/y_test.shape[0]



La tasa de error de cada uno de los 10 pliegues es: 

0.14285714285714285
0.14285714285714285
0.14285714285714285
0.14285714285714285
0.14285714285714285
0.14285714285714285
0.14285714285714285
0.14285714285714285
0.14285714285714285
0.14285714285714285


In [18]:
print("\nLa media de las tasas de error: ", precision/10)


La media de las tasas de error:  0.8463203463203464


### Ejercicio 4:

In [16]:
# Vamos a realizar lo mismo que en los ejercicios anteriores pero para regresión logística. 
# Primero con Hold-out y luego con cross-validation

#### HOLD-OUT

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1./3., random_state=0, stratify=y)

In [90]:
lr = LogisticRegression(random_state = 0, solver='lbfgs',multi_class='auto', max_iter= 500)
lr.fit(X_train, y_train)

ValueError: y should be a 1d array, got an array of shape (2079, 7) instead.

In [20]:
accuracy = lr.score(X_test, y_test)

In [21]:
print("Tasa de aciertos por regresion logística: ", accuracy)

Tasa de aciertos por regresion logística:  0.8948051948051948


In [22]:
X_accuracy = lr.predict(X_test)
print("\nMatriz de Confusión:\n", confusion_matrix(y_test,X_accuracy))


Matriz de Confusión:
 [[105   0   0   0   0   0   5]
 [  2  94   2   0   8   0   4]
 [  5   5  87   0   0   0  13]
 [  0   0   0 110   0   0   0]
 [  0   0   0   0 110   0   0]
 [  0   0   0   0   0 110   0]
 [  1   4  32   0   0   0  73]]


#### VALIDATION-CROSS

In [23]:
rl = LogisticRegression(random_state=0, multi_class='auto', solver='lbfgs', max_iter=500)

In [24]:
tasa = 0
K=10
cv = StratifiedKFold(n_splits=K)
i = 0
print("La tasa de acierto para cada uno de los 10 pliegues es:")
for train_index, test_index in cv.split(X,y):
    
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    rl.fit(X_train, y_train)
    print(rl.score(X_test, y_test))
    i = i+1
    tasa += rl.score(X_test, y_test)

print("\nTasa de acierto:")
print(tasa/K)

La tasa de acierto para cada uno de los 10 pliegues es:
0.9307359307359307
0.9090909090909091
0.9047619047619048
0.9004329004329005
0.9047619047619048
0.9177489177489178
0.8961038961038961
0.8917748917748918
0.9134199134199135
0.8744588744588745

Tasa de acierto:
0.9043290043290044
